// Copyright 2013 Baidu.com  All Rights Reserved.
// Author: tianmo@baidu.com (Mo Tian)
//
// This file automatically generated by template-converter:
//    template-converter default_ctpl default.ctpl
//
// DO NOT EDIT!

#ifndef UNISE_FRONTEND_CTPL_DEFAULT_CTPL_H_
#define UNISE_FRONTEND_CTPL_DEFAULT_CTPL_H_

#include <string>

const std::string default_ctpl(
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\">\n"
"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"    <link href=\"http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css\" rel=\"stylesheet\">\n"
"    <title>Unise Frontend</title>\n"
"    <style type=\"text/css\"> \n"
"        body {\n"
"            padding-top: 70px;\n"
"        }\n"
"        .foot {\n"
"           height:50px;\n"
"           width:100%;\n"
"           background:#EEEEEE;\n"
"           color:#000;\n"
"           font-size:14px;\n"
"           text-align:center;\n"
"        }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"     {{#PAGE_LIST_TAG}}\n"
"     <div class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\" style=\"background-color:#01184A;\">\n"
"      <div class=\"container\">\n"
"        <div class=\"navbar-header\">\n"
"            <span class=\"navbar-brand\" style=\"color: #FFF;font-size:27px;font-weight:bold;\">UniSE Frontend</span>\n"
"        </div>\n"
"        <div class=\"navbar-collapse collapse\">\n"
"          <ul class=\"nav navbar-nav navbar-right\">\n"
"            {{#ONE_PAGE_INFO_LEAD}}\n"
"            {{PAGE_LEAD}}\n"
"            {{/ONE_PAGE_INFO_LEAD}}\n"
"          </ul>\n"
"      </div>\n"
"      </div>\n"
"    </div>\n"
"    <div class=\"container\">\n"
"       <div class=\"jumbotron\">\n"
"        <div style=\"font-size:14px;\">\n"
"         <table style=\"font-size:14px;\" border=\"0\" cellpadding=\"2\" cellspacing=\"0\">\n"
"         <tr height='45px'>\n"
"           <td colspan='4'><p style='line-height:40px'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UniSE，是United Search Engine的简称。是一个通用检索引擎框架，使用das导出的基量数据进行索引，支持das导出的增量数据，用来实时更新索引。UniSE Frontend作为UniSE工作内部集成的调试、检测其是否正常工作的工具。</p></td>\n"
"          </tr>\n"
"          <tr height='45px'>\n"
"           <td colspan='4'><p style='line-height:40px'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;当前使用的UniSE Frontend有如下功能:</p></td>\n"
"          </tr>\n"
"          <tr height='45px'><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td colspan='3'>\n"
"              <table style=\"font-size:14px;\" border=\"1\">\n"
"              <tr height='45px'>\n"
"               <td>Page Id&nbsp;&nbsp;</td><td>Page Name</td><td>Page directory&nbsp;&nbsp;</td><td>Page description</td>\n"
"              </tr>\n"
"              {{#ONE_PAGE_INFO}}\n"
"              <tr height='45px'>\n"
"               <td>{{PAGE_ID}}</td><td>{{PAGE_NAME}}&nbsp;&nbsp;</td><td>{{PAGE_DIR}}</td><td>{{PAGE_INFO}}&nbsp;&nbsp;</td>\n"
"              </tr>\n"
"              {{/ONE_PAGE_INFO}}\n"
"              </table>\n"
"          </td></tr></table>\n"
"         </div>\n"
"         <br>\n"
"         <hr size=\"1\" noshade=\"noshade\" style=\"border:1px #cccccc dotted;\">\n"
"         <div class=\"foot\">Any Question, Contact to vsce@baidu.com<br/>2014-09-17</div>\n"
"       </div>\n"
"  </div>\n"
"  {{/PAGE_LIST_TAG}}\n"
"</body>\n"
"</html>\n"
);

#endif  // UNISE_FRONTEND_CTPL_DEFAULT_CTPL_H_
